# Generated by Django 3.2.8 on 2022-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('subcategory', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
