# Generated by Django 3.2.8 on 2022-11-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_alter_payment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
