# Generated by Django 3.2.8 on 2022-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_rename_user_id_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
