# Generated by Django 3.2.8 on 2023-03-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_alter_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costs.category')),
            ],
        ),
    ]
