# Generated by Django 3.2.8 on 2023-04-13 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0008_venders'),
    ]

    operations = [
        migrations.AddField(
            model_name='venders',
            name='specific',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
